# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    delivery_addresses: ['tuxulakoelmejor@gmail.com', 'i62cogag@uco.es']
